name: Sync Edge Dev Releases

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Edge Dev APK
        uses: Yakov5776/gh-apkmirror-dl@v1.3
        with:
          org: "microsoft-corporation"
          repo: "microsoft-edge-dev"
          bundle: false

      - name: Rename APK File
        run: |
          RAW_FILE=$(ls *.apk | head -n 1)
          mv "$RAW_FILE" "edge-dev.apk"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          name: "Microsoft Edge Dev Latest"
          files: "edge-dev.apk"
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
